### PR TITLE
Responsiveness on mobile, tablets, rotated mobile and machine

### PR DESCRIPTION
**Pull request by Landos007**

### CODE REVIEW

**Comment by DerrickOG** [comment]
@Landos007  there is a displacement issue in  a small laptop display 
here is the screenshot showing the issue : http://prnt.sc/s4kvrz

**Comment by DerrickOG** [comment]
**pop up** issue

Screenshot_91

**Comment by DerrickOG** [comment]
I left the comment it these screenshots 
Screenshot_90
Screenshot_91
Screenshot_92
Screenshot_93

**Comment by DerrickOG** [comment]
@Landos007  iPad landscape fix the home page
Screenshot_94

**Review by musayann — APPROVED** [review]

**Pull request merged**
